language: java
jdk:
  - openjdk11

addons:
  sonarcloud:
    organization: "reynault"
    token: $SECRETVALUE

before_install:
  - cd back

script:
  # the following command line builds the project, 
  # runs the tests with coverage and then execute the SonarCloud analysis
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar

after_deploy:
  - echo "done deploying"